"""baseline

Revision ID: 0001
Revises:
Create Date: 2026-08-26 11:20:09.996515

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adp_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("platform_player_id", sa.String(), nullable=False),
        sa.Column("season", sa.String(), nullable=False),
        sa.Column("format", sa.String(), nullable=False),
        sa.Column("adp", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "platform", "platform_player_id", "season", "format", name="uq_adp_entry"
        ),
    )
    with op.batch_alter_table("adp_entries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_adp_entries_platform"), ["platform"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_adp_entries_platform_player_id"), ["platform_player_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_adp_entries_season"), ["season"], unique=False)

    op.create_table(
        "name_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("source_name_raw", sa.String(), nullable=False),
        sa.Column("normalized_name", sa.String(), nullable=False),
        sa.Column("platform_player_id", sa.String(), nullable=True),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform", "source_type", "normalized_name", name="uq_name_mapping"),
    )
    with op.batch_alter_table("name_mappings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_name_mappings_normalized_name"), ["normalized_name"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_name_mappings_platform"), ["platform"], unique=False)

    op.create_table(
        "platform_players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("platform_player_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("position", sa.String(), nullable=True),
        sa.Column("team", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform", "platform_player_id", name="uq_platform_player"),
    )
    with op.batch_alter_table("platform_players", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_platform_players_platform"), ["platform"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_platform_players_platform_player_id"),
            ["platform_player_id"],
            unique=False,
        )

    op.create_table(
        "rank_sets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("season", sa.String(), nullable=False),
        sa.Column("format", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform", "season", "format", "name", name="uq_rank_set_name"),
    )
    with op.batch_alter_table("rank_sets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rank_sets_format"), ["format"], unique=False)
        batch_op.create_index(batch_op.f("ix_rank_sets_platform"), ["platform"], unique=False)
        batch_op.create_index(batch_op.f("ix_rank_sets_season"), ["season"], unique=False)

    op.create_table(
        "sync_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sync_type", sa.String(), nullable=False),
        sa.Column("season", sa.String(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sync_type", "season", name="uq_sync_status"),
    )
    with op.batch_alter_table("sync_status", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sync_status_sync_type"), ["sync_type"], unique=False)

    op.create_table(
        "leagues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("platform_league_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("season", sa.String(), nullable=False),
        sa.Column("format", sa.String(), nullable=False),
        sa.Column("num_teams", sa.Integer(), nullable=False),
        sa.Column("roster_positions", sa.JSON(), nullable=False),
        sa.Column("team_names", sa.JSON(), nullable=False),
        sa.Column("rank_set_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rank_set_id"],
            ["rank_sets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("leagues", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_leagues_format"), ["format"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_leagues_platform_league_id"), ["platform_league_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_leagues_season"), ["season"], unique=False)

    op.create_table(
        "rank_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rank_set_id", sa.Integer(), nullable=False),
        sa.Column("platform_player_id", sa.String(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rank_set_id"],
            ["rank_sets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rank_set_id", "platform_player_id", name="uq_rank_entry_player"),
    )
    with op.batch_alter_table("rank_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_rank_entries_platform_player_id"), ["platform_player_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_rank_entries_rank_set_id"), ["rank_set_id"], unique=False
        )

    op.create_table(
        "drafts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("platform_draft_id", sa.String(), nullable=True),
        sa.Column("league_id", sa.Integer(), nullable=True),
        sa.Column("season", sa.String(), nullable=False),
        sa.Column("format", sa.String(), nullable=False),
        sa.Column("num_teams", sa.Integer(), nullable=False),
        sa.Column("num_rounds", sa.Integer(), nullable=False),
        sa.Column("my_slot", sa.Integer(), nullable=False),
        sa.Column("team_names", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["leagues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("drafts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_drafts_format"), ["format"], unique=False)
        batch_op.create_index(batch_op.f("ix_drafts_season"), ["season"], unique=False)

    op.create_table(
        "draft_picks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("draft_id", sa.Integer(), nullable=False),
        sa.Column("pick_number", sa.Integer(), nullable=False),
        sa.Column("platform_player_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["drafts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("draft_id", "pick_number", name="uq_draft_pick_number"),
        sa.UniqueConstraint("draft_id", "platform_player_id", name="uq_draft_pick_player"),
    )
    with op.batch_alter_table("draft_picks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_draft_picks_draft_id"), ["draft_id"], unique=False)

    op.create_table(
        "draft_queue_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("draft_id", sa.Integer(), nullable=False),
        sa.Column("platform_player_id", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["drafts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("draft_id", "platform_player_id", name="uq_draft_queue_player"),
    )
    with op.batch_alter_table("draft_queue_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_draft_queue_entries_draft_id"), ["draft_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("draft_queue_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_draft_queue_entries_draft_id"))

    op.drop_table("draft_queue_entries")
    with op.batch_alter_table("draft_picks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_draft_picks_draft_id"))

    op.drop_table("draft_picks")
    with op.batch_alter_table("drafts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_drafts_season"))
        batch_op.drop_index(batch_op.f("ix_drafts_format"))

    op.drop_table("drafts")
    with op.batch_alter_table("rank_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rank_entries_rank_set_id"))
        batch_op.drop_index(batch_op.f("ix_rank_entries_platform_player_id"))

    op.drop_table("rank_entries")
    with op.batch_alter_table("leagues", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_leagues_season"))
        batch_op.drop_index(batch_op.f("ix_leagues_platform_league_id"))
        batch_op.drop_index(batch_op.f("ix_leagues_format"))

    op.drop_table("leagues")
    with op.batch_alter_table("sync_status", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sync_status_sync_type"))

    op.drop_table("sync_status")
    with op.batch_alter_table("rank_sets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rank_sets_season"))
        batch_op.drop_index(batch_op.f("ix_rank_sets_platform"))
        batch_op.drop_index(batch_op.f("ix_rank_sets_format"))

    op.drop_table("rank_sets")
    with op.batch_alter_table("platform_players", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_platform_players_platform_player_id"))
        batch_op.drop_index(batch_op.f("ix_platform_players_platform"))

    op.drop_table("platform_players")
    with op.batch_alter_table("name_mappings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_name_mappings_platform"))
        batch_op.drop_index(batch_op.f("ix_name_mappings_normalized_name"))

    op.drop_table("name_mappings")
    with op.batch_alter_table("adp_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_adp_entries_season"))
        batch_op.drop_index(batch_op.f("ix_adp_entries_platform_player_id"))
        batch_op.drop_index(batch_op.f("ix_adp_entries_platform"))

    op.drop_table("adp_entries")
    # ### end Alembic commands ###
