"""rank set scope and entry tier

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-26 11:27:44.290820

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Hand-written rather than autogenerated: Alembic does not reliably detect
    # a unique-constraint change on SQLite, so the drop/recreate pair below
    # would silently be missing from a generated revision.
    #
    # batch_alter_table is doing real work here -- SQLite has no
    # ALTER TABLE ... DROP CONSTRAINT, so Alembic rebuilds rank_sets with the
    # new definition, copies the rows across (existing sets pick up
    # scope='overall' from the server_default), drops the original and renames.
    # That reflection step is why uq_rank_set_name has to be *named* in
    # models.py: an anonymous constraint has no name to drop.
    with op.batch_alter_table("rank_sets", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("scope", sa.String(), nullable=False, server_default="overall")
        )
        batch_op.drop_constraint("uq_rank_set_name", type_="unique")
        batch_op.create_unique_constraint(
            "uq_rank_set_name", ["platform", "season", "format", "scope", "name"]
        )
        batch_op.create_index(batch_op.f("ix_rank_sets_scope"), ["scope"], unique=False)

    with op.batch_alter_table("rank_entries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tier", sa.Integer(), nullable=True))


def downgrade() -> None:
    with op.batch_alter_table("rank_entries", schema=None) as batch_op:
        batch_op.drop_column("tier")

    with op.batch_alter_table("rank_sets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rank_sets_scope"))
        batch_op.drop_constraint("uq_rank_set_name", type_="unique")
        batch_op.create_unique_constraint(
            "uq_rank_set_name", ["platform", "season", "format", "name"]
        )
        batch_op.drop_column("scope")
