"""rank entry break strength and flag

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-02 11:25:59.966764

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rank_entries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("break_after", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("flag", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rank_entries", schema=None) as batch_op:
        batch_op.drop_column("flag")
        batch_op.drop_column("break_after")

    # ### end Alembic commands ###
