"""corpus documents chunks and mentions

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-02 15:52:49.802469

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | Sequence[str] | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "corpus_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analyst", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("source_filename", sa.String(), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("imported_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("analyst", "title", name="uq_corpus_document_title"),
    )
    with op.batch_alter_table("corpus_documents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_corpus_documents_analyst"), ["analyst"], unique=False)
        batch_op.create_index(batch_op.f("ix_corpus_documents_kind"), ["kind"], unique=False)

    op.create_table(
        "corpus_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["corpus_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "chunk_index", name="uq_corpus_chunk_index"),
    )
    with op.batch_alter_table("corpus_chunks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_corpus_chunks_document_id"), ["document_id"], unique=False
        )

    op.create_table(
        "chunk_mentions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.Integer(), nullable=False),
        sa.Column("source_name_raw", sa.String(), nullable=False),
        sa.Column("normalized_name", sa.String(), nullable=False),
        sa.Column("detected_by", sa.String(), nullable=False),
        sa.Column("occurrences", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["corpus_chunks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chunk_id", "normalized_name", name="uq_chunk_mention"),
    )
    with op.batch_alter_table("chunk_mentions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_chunk_mention_name_chunk", ["normalized_name", "chunk_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_chunk_mentions_chunk_id"), ["chunk_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_chunk_mentions_normalized_name"), ["normalized_name"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chunk_mentions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chunk_mentions_normalized_name"))
        batch_op.drop_index(batch_op.f("ix_chunk_mentions_chunk_id"))
        batch_op.drop_index("ix_chunk_mention_name_chunk")

    op.drop_table("chunk_mentions")
    with op.batch_alter_table("corpus_chunks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_corpus_chunks_document_id"))

    op.drop_table("corpus_chunks")
    with op.batch_alter_table("corpus_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_corpus_documents_kind"))
        batch_op.drop_index(batch_op.f("ix_corpus_documents_analyst"))

    op.drop_table("corpus_documents")
    # ### end Alembic commands ###
